[package]
name = "bench_old_async"
version = "0.1.0"
authors = ["Mario Ortiz Manero <marioortizmanero@gmail.com>"]
edition = "2018"

[dependencies]
rspotify = "0.10.0"
tokio = { version = "0.2.25", features = ["full"] }
